# inherit_from: .rubocop_todo.yml

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - "db/schema.rb"

Metrics/BlockLength:
  Exclude:
    - "db/schema.rb"
