default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: foobar123
  host: localhost
  port: 3306

development:
  <<: *default
  database: prosas_projects_development

test:
  <<: *default
  database: prosas_projects_test

production:
  <<: *default
  database: prosas_projects_production
